const movies = [
  {
    score: 0.9086353,
    show: {
      id: 139,
      url: 'https://www.tvmaze.com/shows/139/girls',
      name: 'Girls',
      type: 'Scripted',
      language: 'English',
      genres: ['Drama', 'Romance'],
      status: 'Ended',
      runtime: 30,
      averageRuntime: 30,
      premiered: '2012-04-15',
      ended: '2017-04-16',
      officialSite: 'http://www.hbo.com/girls',
      schedule: { time: '22:00', days: ['Sunday'] },
      rating: { average: 6.6 },
      weight: 97,
      network: {
        id: 8,
        name: 'HBO',
        country: {
          name: 'United States',
          code: 'US',
          timezone: 'America/New_York',
        },
      },
      webChannel: null,
      dvdCountry: null,
      externals: { tvrage: 30124, thetvdb: 220411, imdb: 'tt1723816' },
      image: {
        medium:
          'https://static.tvmaze.com/uploads/images/medium_portrait/31/78286.jpg',
        original:
          'https://static.tvmaze.com/uploads/images/original_untouched/31/78286.jpg',
      },
      summary:
        '<p>This Emmy winning series is a comic look at the assorted humiliations and rare triumphs of a group of girls in their 20s.</p>',
      updated: 1611310521,
      _links: {
        self: { href: 'https://api.tvmaze.com/shows/139' },
        previousepisode: { href: 'https://api.tvmaze.com/episodes/1079686' },
      },
    },
  },
  {
    score: 0.8905322,
    show: {
      id: 41734,
      url: 'https://www.tvmaze.com/shows/41734/girls',
      name: 'GIRLS',
      type: 'Scripted',
      language: 'Mongolian',
      genres: ['Comedy'],
      status: 'Ended',
      runtime: 41,
      averageRuntime: null,
      premiered: null,
      ended: null,
      officialSite: null,
      schedule: { time: '', days: ['Thursday'] },
      rating: { average: null },
      weight: 51,
      network: {
        id: 1672,
        name: 'UBS',
        country: { name: 'Mongolia', code: 'MN', timezone: 'Asia/Ulaanbaatar' },
      },
      webChannel: null,
      dvdCountry: null,
      externals: { tvrage: null, thetvdb: null, imdb: 'tt8709752' },
      image: {
        medium:
          'https://static.tvmaze.com/uploads/images/medium_portrait/191/478539.jpg',
        original:
          'https://static.tvmaze.com/uploads/images/original_untouched/191/478539.jpg',
      },
      summary: null,
      updated: 1632080861,
      _links: { self: { href: 'https://api.tvmaze.com/shows/41734' } },
    },
  },
  {
    score: 0.70129347,
    show: {
      id: 23542,
      url: 'https://www.tvmaze.com/shows/23542/good-girls',
      name: 'Good Girls',
      type: 'Scripted',
      language: 'English',
      genres: ['Drama', 'Comedy', 'Crime'],
      status: 'Ended',
      runtime: 60,
      averageRuntime: 60,
      premiered: '2018-02-26',
      ended: '2021-07-22',
      officialSite: 'https://www.nbc.com/good-girls',
      schedule: { time: '21:00', days: ['Thursday'] },
      rating: { average: 7.3 },
      weight: 97,
      network: {
        id: 1,
        name: 'NBC',
        country: {
          name: 'United States',
          code: 'US',
          timezone: 'America/New_York',
        },
      },
      webChannel: null,
      dvdCountry: null,
      externals: { tvrage: null, thetvdb: 328577, imdb: 'tt6474378' },
      image: {
        medium:
          'https://static.tvmaze.com/uploads/images/medium_portrait/297/744253.jpg',
        original:
          'https://static.tvmaze.com/uploads/images/original_untouched/297/744253.jpg',
      },
      summary:
        '<p><b>Good Girls</b> follows three "good girl" suburban wives and mothers who suddenly find themselves in desperate circumstances and decide to stop playing it safe, and risk everything to take their power back.</p>',
      updated: 1627294164,
      _links: {
        self: { href: 'https://api.tvmaze.com/shows/23542' },
        previousepisode: { href: 'https://api.tvmaze.com/episodes/2108575' },
      },
    },
  },
  {
    score: 0.70113546,
    show: {
      id: 33320,
      url: 'https://www.tvmaze.com/shows/33320/derry-girls',
      name: 'Derry Girls',
      type: 'Scripted',
      language: 'English',
      genres: ['Comedy'],
      status: 'Running',
      runtime: 30,
      averageRuntime: 30,
      premiered: '2018-01-04',
      ended: null,
      officialSite: 'http://www.channel4.com/programmes/derry-girls',
      schedule: { time: '22:00', days: ['Tuesday'] },
      rating: { average: 8.2 },
      weight: 93,
      network: {
        id: 45,
        name: 'Channel 4',
        country: {
          name: 'United Kingdom',
          code: 'GB',
          timezone: 'Europe/London',
        },
      },
      webChannel: null,
      dvdCountry: null,
      externals: { tvrage: null, thetvdb: 338903, imdb: 'tt7120662' },
      image: {
        medium:
          'https://static.tvmaze.com/uploads/images/medium_portrait/184/460240.jpg',
        original:
          'https://static.tvmaze.com/uploads/images/original_untouched/184/460240.jpg',
      },
      summary:
        "<p>16-year-old Erin Quinn lives with her uncompromising mother, her long-suffering father and the fearsome ‘Granda Joe', a man whose love for his daughters and granddaughters is surpassed only by his contempt for his son-in-law.</p><p>It's the early 90s, and Erin is used to seeing her country on the nightly news and speaking in acronyms (The IRA, The UDA, The RUC). This is a time of armed police in armoured Land Rovers and British Army check points. But it's also the time of Murder She Wrote, The Cranberries, MJ and Lisa Marie, Doc Martens, bomber jackets, The X Files, Nirvana and Wayne's World. And while The Troubles may hang over her home town, Erin has troubles of her own</p>",
      updated: 1637594376,
      _links: {
        self: { href: 'https://api.tvmaze.com/shows/33320' },
        previousepisode: { href: 'https://api.tvmaze.com/episodes/1631064' },
      },
    },
  },
  {
    score: 0.7009764,
    show: {
      id: 525,
      url: 'https://www.tvmaze.com/shows/525/gilmore-girls',
      name: 'Gilmore Girls',
      type: 'Scripted',
      language: 'English',
      genres: ['Drama', 'Comedy', 'Romance'],
      status: 'Ended',
      runtime: 60,
      averageRuntime: 60,
      premiered: '2000-10-05',
      ended: '2007-05-15',
      officialSite: null,
      schedule: { time: '21:00', days: ['Tuesday'] },
      rating: { average: 8.4 },
      weight: 95,
      network: {
        id: 5,
        name: 'The CW',
        country: {
          name: 'United States',
          code: 'US',
          timezone: 'America/New_York',
        },
      },
      webChannel: null,
      dvdCountry: null,
      externals: { tvrage: 3683, thetvdb: 76568, imdb: 'tt0238784' },
      image: {
        medium:
          'https://static.tvmaze.com/uploads/images/medium_portrait/4/11308.jpg',
        original:
          'https://static.tvmaze.com/uploads/images/original_untouched/4/11308.jpg',
      },
      summary:
        '<p><b>Gilmore Girls</b> is a drama centering around the relationship between a thirtysomething single mother and her teen daughter living in Stars Hollow, Connecticut.</p>',
      updated: 1618158592,
      _links: {
        self: { href: 'https://api.tvmaze.com/shows/525' },
        previousepisode: { href: 'https://api.tvmaze.com/episodes/47639' },
      },
    },
  },
  {
    score: 0.6984602,
    show: {
      id: 42986,
      url: 'https://www.tvmaze.com/shows/42986/paper-girls',
      name: 'Paper Girls',
      type: 'Scripted',
      language: 'English',
      genres: ['Drama', 'Science-Fiction'],
      status: 'In Development',
      runtime: null,
      averageRuntime: null,
      premiered: null,
      ended: null,
      officialSite: null,
      schedule: { time: '', days: [] },
      rating: { average: null },
      weight: 77,
      network: null,
      webChannel: { id: 3, name: 'Amazon Prime Video', country: null },
      dvdCountry: null,
      externals: { tvrage: null, thetvdb: 368187, imdb: 'tt10623646' },
      image: null,
      summary:
        '<p><b>Paper Girls </b>follows four young girls who, while out delivering papers on the morning after Halloween in 1988, become unwittingly caught in a conflict between warring factions of time-travelers, sending them on an adventure through time that will save the world. As they travel between our present, the past, and the future — they encounter future versions of themselves and now must choose to embrace or reject their fate. An emotional adventure in which the girls and the women they eventually become are tough, their friendships are authentic, and their journey through time is epic.</p>',
      updated: 1623788103,
      _links: { self: { href: 'https://api.tvmaze.com/shows/42986' } },
    },
  },
  {
    score: 0.6971027,
    show: {
      id: 1073,
      url: 'https://www.tvmaze.com/shows/1073/bomb-girls',
      name: 'Bomb Girls',
      type: 'Scripted',
      language: 'English',
      genres: ['Drama', 'Romance', 'War'],
      status: 'Ended',
      runtime: 60,
      averageRuntime: 60,
      premiered: '2012-01-04',
      ended: '2013-04-29',
      officialSite: null,
      schedule: { time: '20:00', days: ['Monday'] },
      rating: { average: 8.8 },
      weight: 47,
      network: {
        id: 67,
        name: 'Global',
        country: { name: 'Canada', code: 'CA', timezone: 'America/Halifax' },
      },
      webChannel: null,
      dvdCountry: null,
      externals: { tvrage: 30600, thetvdb: 254378, imdb: 'tt1955311' },
      image: {
        medium:
          'https://static.tvmaze.com/uploads/images/medium_portrait/7/17549.jpg',
        original:
          'https://static.tvmaze.com/uploads/images/original_untouched/7/17549.jpg',
      },
      summary:
        '<p>Set in the 1940s, <b>Bomb Girls</b> tells the remarkable stories of the women who risked their lives in a munitions factory building bombs for the Allied forces fighting on the European front. The series delves into the lives of these exceptional women – peers, friends and rivals – who find themselves thrust into new worlds and changed profoundly as they are liberated from their home and social restrictions.</p>',
      updated: 1592496010,
      _links: {
        self: { href: 'https://api.tvmaze.com/shows/1073' },
        previousepisode: { href: 'https://api.tvmaze.com/episodes/108024' },
      },
    },
  },
  {
    score: 0.6968226,
    show: {
      id: 3418,
      url: 'https://www.tvmaze.com/shows/3418/anzac-girls',
      name: 'ANZAC Girls',
      type: 'Scripted',
      language: 'English',
      genres: ['Drama', 'War', 'History'],
      status: 'Ended',
      runtime: 60,
      averageRuntime: 60,
      premiered: '2014-08-10',
      ended: '2014-09-14',
      officialSite: 'http://www.abc.net.au/tv/programs/anzac-girls/',
      schedule: { time: '20:30', days: ['Sunday'] },
      rating: { average: 7.3 },
      weight: 63,
      network: {
        id: 114,
        name: 'ABC',
        country: {
          name: 'Australia',
          code: 'AU',
          timezone: 'Australia/Sydney',
        },
      },
      webChannel: null,
      dvdCountry: null,
      externals: { tvrage: 43688, thetvdb: 284182, imdb: 'tt3078602' },
      image: {
        medium:
          'https://static.tvmaze.com/uploads/images/medium_portrait/17/44896.jpg',
        original:
          'https://static.tvmaze.com/uploads/images/original_untouched/17/44896.jpg',
      },
      summary:
        '<p>Honouring the Centenary of the commencement of WW1, <b>ANZAC Girls</b> is a moving new six-part series based on the unique, and rarely told true stories of Australian and New Zealand nurses serving at Gallipoli and the Western Front.</p>',
      updated: 1586354019,
      _links: {
        self: { href: 'https://api.tvmaze.com/shows/3418' },
        previousepisode: { href: 'https://api.tvmaze.com/episodes/226941' },
      },
    },
  },
  {
    score: 0.69644445,
    show: {
      id: 42726,
      url: 'https://www.tvmaze.com/shows/42726/florida-girls',
      name: 'Florida Girls',
      type: 'Scripted',
      language: 'English',
      genres: ['Comedy'],
      status: 'Ended',
      runtime: 30,
      averageRuntime: 30,
      premiered: '2019-07-10',
      ended: '2019-08-07',
      officialSite: 'https://poptv.com/floridagirls',
      schedule: { time: '22:00', days: ['Wednesday'] },
      rating: { average: 6.5 },
      weight: 46,
      network: {
        id: 88,
        name: 'Pop',
        country: {
          name: 'United States',
          code: 'US',
          timezone: 'America/New_York',
        },
      },
      webChannel: null,
      dvdCountry: null,
      externals: { tvrage: null, thetvdb: 363682, imdb: 'tt8548870' },
      image: {
        medium:
          'https://static.tvmaze.com/uploads/images/medium_portrait/203/508390.jpg',
        original:
          'https://static.tvmaze.com/uploads/images/original_untouched/203/508390.jpg',
      },
      summary:
        "<p><b>Florida Girls</b> follows four women who are forced to confront their stagnant lives when their only ambitious friend moves away to follow her dreams. Bound by their friendship, they will attempt to navigate life's curveballs while living below the poverty line.</p>",
      updated: 1583390100,
      _links: {
        self: { href: 'https://api.tvmaze.com/shows/42726' },
        previousepisode: { href: 'https://api.tvmaze.com/episodes/1673960' },
      },
    },
  },
  {
    score: 0.6963491,
    show: {
      id: 49334,
      url: 'https://www.tvmaze.com/shows/49334/shining-girls',
      name: 'Shining Girls',
      type: 'Scripted',
      language: 'English',
      genres: ['Thriller'],
      status: 'In Development',
      runtime: null,
      averageRuntime: null,
      premiered: null,
      ended: null,
      officialSite: null,
      schedule: { time: '', days: [] },
      rating: { average: null },
      weight: 81,
      network: null,
      webChannel: { id: 310, name: 'Apple TV+', country: null },
      dvdCountry: null,
      externals: { tvrage: null, thetvdb: null, imdb: null },
      image: null,
      summary:
        '<p><b>Shining Girls</b> is a metaphysical thriller, which follows a Chicago reporter who survived a brutal assault only to find her reality shifting as she hunts down her attacker.</p>',
      updated: 1627022370,
      _links: { self: { href: 'https://api.tvmaze.com/shows/49334' } },
    },
  },
];

export default movies;